language: node_js
node_js:
  - "node"
script:
  - npm run build
deploy:
  provider: pages
  local_dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Secure variable
  keep-history: true
  on:
    branch: master